-- ============================================================
--  003 - Productos Ferrepro + Meta Ads
--  Base: Supabase / PostgreSQL   ·   schema: public
-- ============================================================
--  Objetos propios de Ferrepro usados por dashboard/agente:
--    - productos Tiendanube + variantes + busqueda RAG
--    - estado incremental de productos
--    - insights diarios de Meta Ads + helpers del dashboard
-- ============================================================

create extension if not exists vector;
create extension if not exists unaccent;
create extension if not exists pg_trgm;

do $$
begin
  create type public.meta_level as enum ('account', 'campaign', 'adset', 'ad');
exception
  when duplicate_object then null;
end;
$$;

create table if not exists public.ferrepro_productos (
  id              bigint primary key,
  name            text not null,
  description     text,
  brand           text,
  handle          text,
  canonical_url   text,
  published       boolean,
  is_kit          boolean,
  has_stock       boolean,
  tags            text[] default '{}',
  category_ids    bigint[] default '{}',
  category_names  text[] default '{}',
  primary_image   text,
  price_min       numeric,
  price_max       numeric,
  total_stock     integer,
  in_stock        boolean default false,
  tn_created_at   timestamptz,
  tn_updated_at   timestamptz,
  synced_at       timestamptz default now(),
  raw             jsonb,
  search_text     text,
  search_vector   tsvector,
  embedding       vector(1536)
);

create table if not exists public.ferrepro_variantes (
  id                 bigint primary key,
  product_id         bigint references public.ferrepro_productos(id) on delete cascade,
  sku                text,
  barcode            text,
  values             jsonb,
  price              numeric,
  promotional_price  numeric,
  stock              integer,
  stock_management   boolean,
  weight             numeric,
  position           integer
);

create table if not exists public.ferrepro_sync_state (
  id           integer primary key default 1,
  last_run_at  timestamptz,
  updated_at   timestamptz default now(),
  constraint ferrepro_sync_state_singleton check (id = 1)
);

insert into public.ferrepro_sync_state (id)
values (1)
on conflict (id) do nothing;

create table if not exists public.meta_insights_daily (
  id                    bigint generated by default as identity primary key,
  level                 public.meta_level not null,
  entity_id             text not null,
  entity_name           text,
  date_start            date not null,
  date_stop             date not null,
  impressions           bigint,
  clicks                bigint,
  reach                 bigint,
  spend                 numeric,
  cpc                   numeric,
  cpm                   numeric,
  ctr                   numeric,
  frequency             numeric,
  cpp                   numeric,
  actions               jsonb,
  cost_per_action_type  jsonb,
  raw                   jsonb,
  created_at            timestamptz not null default now()
);

create or replace function public.ferrepro_productos_set_search_vector()
  returns trigger
  language plpgsql
as $$
begin
  new.search_vector := to_tsvector('spanish', coalesce(new.search_text, ''));
  return new;
end;
$$;

drop trigger if exists trg_ferrepro_productos_search_vector on public.ferrepro_productos;
create trigger trg_ferrepro_productos_search_vector
  before insert or update of search_text
  on public.ferrepro_productos
  for each row execute function public.ferrepro_productos_set_search_vector();

create index if not exists ferrepro_productos_in_stock_idx
  on public.ferrepro_productos (in_stock) where in_stock;
create index if not exists ferrepro_productos_search_vector_idx
  on public.ferrepro_productos using gin (search_vector);
create index if not exists ferrepro_productos_search_trgm_idx
  on public.ferrepro_productos using gin (search_text gin_trgm_ops);
create index if not exists ferrepro_productos_embedding_idx
  on public.ferrepro_productos using hnsw (embedding vector_cosine_ops);
create index if not exists ferrepro_variantes_producto_idx
  on public.ferrepro_variantes (product_id);
create index if not exists ferrepro_variantes_sku_idx
  on public.ferrepro_variantes (sku);
create index if not exists idx_meta_insights_daily_entity
  on public.meta_insights_daily (level, entity_id, date_start);
create unique index if not exists meta_insights_daily_uniq
  on public.meta_insights_daily (level, entity_id, date_start);

create or replace function public.ferrepro_upsert_producto(
  p_payload jsonb,
  p_embedding vector default null::vector
)
  returns void
  language plpgsql
  security definer
  set search_path to 'public'
as $$
declare
  v_id          bigint := (p_payload->>'id')::bigint;
  v_price_min   numeric;
  v_price_max   numeric;
  v_total_stock integer;
  v_in_stock    boolean;
begin
  select
    min((v->>'price')::numeric),
    max((v->>'price')::numeric),
    case when bool_or((v->>'stock') is null) then null
         else coalesce(sum((v->>'stock')::int), 0) end,
    coalesce(bool_or((v->>'stock') is null or (v->>'stock')::int > 0), false)
  into v_price_min, v_price_max, v_total_stock, v_in_stock
  from jsonb_array_elements(coalesce(p_payload->'variants', '[]'::jsonb)) v;

  insert into public.ferrepro_productos as p (
    id, name, description, brand, handle, canonical_url,
    published, is_kit, has_stock, tags, category_ids, category_names,
    primary_image, price_min, price_max, total_stock, in_stock,
    tn_created_at, tn_updated_at, synced_at, raw, search_text, embedding
  ) values (
    v_id,
    p_payload->>'name',
    p_payload->>'description',
    p_payload->>'brand',
    p_payload->>'handle',
    p_payload->>'canonical_url',
    (p_payload->>'published')::boolean,
    (p_payload->>'is_kit')::boolean,
    (p_payload->>'has_stock')::boolean,
    coalesce((select array_agg(value) from jsonb_array_elements_text(p_payload->'tags')), '{}'),
    coalesce((select array_agg(value::bigint) from jsonb_array_elements_text(p_payload->'category_ids')), '{}'),
    coalesce((select array_agg(value) from jsonb_array_elements_text(p_payload->'category_names')), '{}'),
    p_payload->>'primary_image',
    v_price_min, v_price_max, v_total_stock, v_in_stock,
    (p_payload->>'tn_created_at')::timestamptz,
    (p_payload->>'tn_updated_at')::timestamptz,
    now(),
    p_payload->'raw',
    lower(unaccent(coalesce(p_payload->>'search_text', ''))),
    p_embedding
  )
  on conflict (id) do update set
    name           = excluded.name,
    description    = excluded.description,
    brand          = excluded.brand,
    handle         = excluded.handle,
    canonical_url  = excluded.canonical_url,
    published      = excluded.published,
    is_kit         = excluded.is_kit,
    has_stock      = excluded.has_stock,
    tags           = excluded.tags,
    category_ids   = excluded.category_ids,
    category_names = excluded.category_names,
    primary_image  = excluded.primary_image,
    price_min      = excluded.price_min,
    price_max      = excluded.price_max,
    total_stock    = excluded.total_stock,
    in_stock       = excluded.in_stock,
    tn_created_at  = excluded.tn_created_at,
    tn_updated_at  = excluded.tn_updated_at,
    synced_at      = now(),
    raw            = excluded.raw,
    search_text    = excluded.search_text,
    embedding      = coalesce(excluded.embedding, p.embedding);

  delete from public.ferrepro_variantes where product_id = v_id;

  insert into public.ferrepro_variantes (
    id, product_id, sku, barcode, values, price, promotional_price,
    stock, stock_management, weight, position
  )
  select
    (v->>'id')::bigint, v_id, v->>'sku', v->>'barcode', v->'values',
    (v->>'price')::numeric, (v->>'promotional_price')::numeric,
    (v->>'stock')::int, (v->>'stock_management')::boolean,
    (v->>'weight')::numeric, (v->>'position')::int
  from jsonb_array_elements(coalesce(p_payload->'variants', '[]'::jsonb)) v;
end;
$$;

create or replace function public.ferrepro_reconciliar(p_ids bigint[])
  returns integer
  language plpgsql
  security definer
  set search_path to 'public'
as $$
declare
  v_deleted integer;
begin
  if p_ids is null or array_length(p_ids, 1) is null then
    return 0;
  end if;

  delete from public.ferrepro_productos where id <> all(p_ids);
  get diagnostics v_deleted = row_count;
  return v_deleted;
end;
$$;

create or replace function public.ferrepro_buscar_productos(
  consulta text,
  query_embedding vector default null::vector,
  solo_con_stock boolean default true,
  limite integer default 8
)
  returns table(
    id bigint,
    name text,
    brand text,
    description text,
    category_names text[],
    price_min numeric,
    price_max numeric,
    in_stock boolean,
    total_stock integer,
    primary_image text,
    canonical_url text,
    score double precision
  )
  language sql
  stable
  security definer
  set search_path to 'public'
as $$
  with q as (
    select lower(unaccent(coalesce(consulta, ''))) as nq
  ),
  lexico as (
    select p.id,
           row_number() over (
             order by ts_rank(p.search_vector, plainto_tsquery('spanish', (select nq from q))) desc,
                      similarity(p.search_text, (select nq from q)) desc
           ) as rnk
    from public.ferrepro_productos p
    where p.published is true
      and (not solo_con_stock or p.in_stock)
      and (
            p.search_vector @@ plainto_tsquery('spanish', (select nq from q))
        or  p.search_text %  (select nq from q)
      )
    limit 50
  ),
  semantico as (
    select p.id,
           row_number() over (order by p.embedding <=> query_embedding) as rnk
    from public.ferrepro_productos p
    where query_embedding is not null
      and p.embedding is not null
      and p.published is true
      and (not solo_con_stock or p.in_stock)
    order by p.embedding <=> query_embedding
    limit 50
  ),
  fusion as (
    select coalesce(l.id, s.id) as id,
           coalesce(1.0 / (60 + l.rnk), 0) + coalesce(1.0 / (60 + s.rnk), 0) as score
    from lexico l
    full outer join semantico s on s.id = l.id
  )
  select p.id, p.name, p.brand, p.description, p.category_names,
         p.price_min, p.price_max, p.in_stock, p.total_stock,
         p.primary_image, p.canonical_url, f.score
  from fusion f
  join public.ferrepro_productos p on p.id = f.id
  order by f.score desc
  limit limite;
$$;

create or replace function public.meta_action_value(actions jsonb, p_action_type text)
  returns numeric
  language sql
  immutable
as $$
  select coalesce((
    select (elem->>'value')::numeric
    from jsonb_array_elements(coalesce(actions, '[]'::jsonb)) as elem
    where elem->>'action_type' = p_action_type
    limit 1
  ), 0);
$$;

create or replace function public.meta_home_summary_mixed(
  p_from date,
  p_to date,
  p_conv_level meta_level default 'campaign'::meta_level
)
  returns table(
    spend_total numeric,
    impressions_total bigint,
    reach_total bigint,
    clicks_total bigint,
    conversations_started numeric,
    cac numeric,
    ctr numeric,
    cpc numeric,
    cpm numeric
  )
  language sql
  stable
as $$
  with acc as (
    select
      sum(coalesce(spend, 0))::numeric as spend_total,
      sum(coalesce(impressions, 0))::bigint as impressions_total,
      sum(coalesce(reach, 0))::bigint as reach_total,
      sum(coalesce(clicks, 0))::bigint as clicks_total
    from public.meta_insights_daily
    where date_start between p_from and p_to
      and level = 'account'
  ),
  conv as (
    select
      sum(public.meta_action_value(actions, 'onsite_conversion.messaging_conversation_started_7d'))::numeric as conversations_started
    from public.meta_insights_daily
    where date_start between p_from and p_to
      and level = p_conv_level
  )
  select
    a.spend_total,
    a.impressions_total,
    a.reach_total,
    a.clicks_total,
    c.conversations_started,
    case when c.conversations_started > 0 then a.spend_total / c.conversations_started else null end,
    case when a.impressions_total > 0 then (a.clicks_total::numeric / a.impressions_total::numeric) * 100 else null end,
    case when a.clicks_total > 0 then a.spend_total / a.clicks_total::numeric else null end,
    case when a.impressions_total > 0 then (a.spend_total / a.impressions_total::numeric) * 1000 else null end
  from acc a cross join conv c;
$$;

create or replace function public.meta_home_timeseries_mixed(
  p_from date,
  p_to date,
  p_compare text default 'prev'::text,
  p_conv_level meta_level default 'campaign'::meta_level
)
  returns table(
    day date,
    spend_actual numeric,
    spend_compare numeric,
    conv_actual bigint,
    conv_compare bigint,
    cac_actual numeric,
    cac_compare numeric
  )
  language sql
  stable
as $$
with
len as (
  select (p_to - p_from + 1)::int as n
),
shift as (
  select case
    when lower(p_compare) = 'yoy' then interval '1 year'
    else (select (n || ' days')::interval from len)
  end as iv
),
days as (
  select generate_series(p_from, p_to, interval '1 day')::date as day
),
actual as (
  select
    date_start::date as day,
    coalesce(sum(spend), 0) as spend,
    coalesce(sum(public.meta_action_value(actions, 'onsite_conversion.messaging_conversation_started_7d')), 0) as conv
  from public.meta_insights_daily
  where level = p_conv_level
    and date_start::date between p_from and p_to
  group by 1
),
cmp as (
  select
    date_start::date as day,
    coalesce(sum(spend), 0) as spend,
    coalesce(sum(public.meta_action_value(actions, 'onsite_conversion.messaging_conversation_started_7d')), 0) as conv
  from public.meta_insights_daily
  where level = p_conv_level
    and date_start::date between (p_from - (select iv from shift))::date
                            and (p_to - (select iv from shift))::date
  group by 1
),
joined as (
  select
    d.day,
    coalesce(a.spend, 0)::numeric as spend_actual,
    coalesce(a.conv, 0)::bigint as conv_actual,
    case when c.day is null then null else coalesce(c.spend, 0)::numeric end as spend_compare,
    case when c.day is null then null else coalesce(c.conv, 0)::bigint end as conv_compare,
    case when coalesce(a.conv, 0) > 0 then (a.spend / a.conv) else null end as cac_actual,
    case when c.day is not null and coalesce(c.conv, 0) > 0 then (c.spend / c.conv) else null end as cac_compare
  from days d
  left join actual a on a.day = d.day
  left join cmp c on c.day = (d.day - (select iv from shift))::date
)
select *
from joined
where spend_actual > 0 or conv_actual > 0
   or (spend_compare is not null and spend_compare > 0)
   or (conv_compare is not null and conv_compare > 0)
order by day;
$$;

create or replace function public.meta_ranking_reco_by_level(
  p_from date,
  p_to date,
  p_level meta_level,
  p_limit integer default 50,
  p_min_conversations numeric default 5,
  p_cac_objetivo numeric default 300,
  p_ctr_min numeric default 1.5,
  p_freq_max numeric default 3.0
)
  returns table(
    entity_id text,
    entity_name text,
    spend numeric,
    conversations_started numeric,
    cac numeric,
    impressions bigint,
    reach bigint,
    clicks bigint,
    ctr numeric,
    cpc numeric,
    cpm numeric,
    frequency numeric,
    accion_recomendada text,
    motivo text
  )
  language sql
  stable
as $$
  with base as (
    select
      entity_id,
      coalesce(entity_name, '(sin nombre)') as entity_name,
      coalesce(spend, 0)::numeric as spend,
      coalesce(impressions, 0)::bigint as impressions,
      coalesce(reach, 0)::bigint as reach,
      coalesce(clicks, 0)::bigint as clicks,
      frequency::numeric as frequency,
      public.meta_action_value(actions, 'onsite_conversion.messaging_conversation_started_7d') as conv
    from public.meta_insights_daily
    where date_start between p_from and p_to
      and level = p_level
  ),
  agg as (
    select
      entity_id,
      max(entity_name) as entity_name,
      sum(spend) as spend,
      sum(conv) as conversations_started,
      sum(impressions) as impressions,
      sum(reach) as reach,
      sum(clicks) as clicks,
      case
        when sum(impressions) > 0
        then sum(frequency * impressions::numeric) / sum(impressions)::numeric
        else null
      end as frequency
    from base
    group by entity_id
  ),
  scored as (
    select
      entity_id,
      entity_name,
      spend,
      conversations_started,
      case when conversations_started > 0 then spend / conversations_started else null end as cac,
      impressions,
      reach,
      clicks,
      case when impressions > 0 then (clicks::numeric / impressions::numeric) * 100 else null end as ctr,
      case when clicks > 0 then spend / clicks::numeric else null end as cpc,
      case when impressions > 0 then (spend / impressions::numeric) * 1000 else null end as cpm,
      frequency
    from agg
    where conversations_started >= p_min_conversations
  )
  select
    s.*,
    case
      when s.frequency is not null and s.frequency >= p_freq_max and s.cac is not null and s.cac > p_cac_objetivo
        then 'SATURACION'
      when s.ctr is not null and s.ctr < p_ctr_min
        then 'REVISAR_ARTE'
      when s.cac is not null and s.cac <= p_cac_objetivo and (s.ctr is null or s.ctr >= p_ctr_min)
        then 'ESCALAR'
      when s.cac is not null and s.cac > (p_cac_objetivo * 1.35)
        then 'PAUSAR'
      else 'MANTENER'
    end as accion_recomendada,
    trim(both ' |' from (
      case when s.cac is not null then 'CAC=' || round(s.cac, 2) || ' (obj ' || round(p_cac_objetivo, 2) || ')' else '' end ||
      case when s.ctr is not null then ' | CTR=' || round(s.ctr, 2) || '% (min ' || round(p_ctr_min, 2) || '%)' else '' end ||
      case when s.frequency is not null then ' | Freq=' || round(s.frequency, 2) || ' (max ' || round(p_freq_max, 2) || ')' else '' end
    )) as motivo
  from scored s
  order by s.cac asc nulls last, s.conversations_started desc
  limit p_limit;
$$;

create or replace function public.meta_campaign_ranking_reco(
  p_from date,
  p_to date,
  p_limit integer default 50,
  p_min_conversations numeric default 5,
  p_cac_objetivo numeric default 300,
  p_ctr_min numeric default 1.5,
  p_freq_max numeric default 3.0
)
  returns table(
    campaign_id text,
    campaign_name text,
    spend numeric,
    conversations_started numeric,
    cac numeric,
    impressions bigint,
    reach bigint,
    clicks bigint,
    ctr numeric,
    cpc numeric,
    cpm numeric,
    frequency numeric,
    accion_recomendada text,
    motivo text
  )
  language sql
  stable
as $$
  select
    entity_id,
    entity_name,
    spend,
    conversations_started,
    cac,
    impressions,
    reach,
    clicks,
    ctr,
    cpc,
    cpm,
    frequency,
    accion_recomendada,
    motivo
  from public.meta_ranking_reco_by_level(
    p_from, p_to, 'campaign',
    p_limit, p_min_conversations,
    p_cac_objetivo, p_ctr_min, p_freq_max
  );
$$;

create or replace function public.meta_adset_ranking_reco(
  p_from date,
  p_to date,
  p_limit integer default 50,
  p_min_conversations numeric default 5,
  p_cac_objetivo numeric default 300,
  p_ctr_min numeric default 1.5,
  p_freq_max numeric default 3.0
)
  returns table(
    adset_id text,
    adset_name text,
    spend numeric,
    conversations_started numeric,
    cac numeric,
    impressions bigint,
    reach bigint,
    clicks bigint,
    ctr numeric,
    cpc numeric,
    cpm numeric,
    frequency numeric,
    accion_recomendada text,
    motivo text
  )
  language sql
  stable
as $$
  select
    entity_id,
    entity_name,
    spend,
    conversations_started,
    cac,
    impressions,
    reach,
    clicks,
    ctr,
    cpc,
    cpm,
    frequency,
    accion_recomendada,
    motivo
  from public.meta_ranking_reco_by_level(
    p_from, p_to, 'adset',
    p_limit, p_min_conversations,
    p_cac_objetivo, p_ctr_min, p_freq_max
  );
$$;
